Test multiple GHCs on Travis-CI

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,5 +1,42 @@
-language: haskell
+env:
+  - CABALVER=1.18 GHCVER=7.6.3
+  - CABALVER=1.18 GHCVER=7.8.3
+  - CABALVER=1.22 GHCVER=7.10.1
+
+before_install:
+  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+  - travis_retry sudo apt-get update
+  - travis_retry sudo apt-get -qq -y install cabal-install-$CABALVER ghc-$GHCVER cpphs
+  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
+
+install:
+  - cabal --version
+  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+  - travis_retry cabal update
+  - |
+    if [ $GHCVER = "head" ] || [ ${GHCVER%.*} = "7.8" ]  || [ ${GHCVER%.*} = "7.10" ]; then
+      travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3
+      export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
+    else
+      travis_retry sudo apt-get install happy alex
+    fi
+  
+  - cabal install --dependencies-only --enable-tests
 
 script:
-  - cabal configure --enable-tests && cabal build && cabal test testexe
+  - cabal configure --enable-tests
+  - cabal build
+  - cabal test testexe
+  - cabal check
+  - cabal sdist
+
+# The following scriptlet checks that the resulting source distribution can be built & installed
+  - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+    cd dist/;
+    if [ -f "$SRC_TGZ" ]; then
+       cabal install --force-reinstalls "$SRC_TGZ";
+    else
+       echo "expected '$SRC_TGZ' not found";
+       exit 1;
+    fi
 
